import { StyleSheet, Dimensions } from 'react-native';
import colors from '../../../../constants/colors';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  // Modern Header Styles
  modernHeader: {
    backgroundColor: colors.mainColor,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
  },
  headerAccentOne: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 200,
    backgroundColor: 'rgba(255,255,255,0.15)',
    top: -60,
    right: -40,
  },
  headerAccentTwo: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 140,
    backgroundColor: 'rgba(255,255,255,0.08)',
    bottom: -40,
    left: -30,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  greetingContainer: {
    marginLeft: 12,
    flex: 1,
  },
  addressText: {
    marginTop: 2,
    maxWidth: width - 150,
  },
  profileIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  headerLogo: {
    width: 48,
    height: 48,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    padding: 6,
    backgroundColor: colors.white,
  },
  heroTitle: {
    fontSize: 20,
  },
  buttonWrapper: {
    flex: 1,
  },
  bannerCtaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    height: 42,
    borderWidth: 1.5,
    borderColor: 'rgba(18, 79, 139, 0.15)',
    paddingHorizontal: 8,
  },
  bannerCtaText: {
    fontSize: 14,
  },
  heroStatsRow: {
    flexDirection: 'row',
    marginTop: 10,
    gap: 10,
  },
  heroStatCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  promoContainer: {
    paddingHorizontal: 10,
    marginTop: 5,
  },
  promoSliderWrapper: {
    paddingHorizontal: 10,
    overflow: 'hidden',
    paddingTop: 10,
  },
  promoSliderPlaceholder: {
    width: '100%',
    height: 160,
    backgroundColor: '#E8ECF2',
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sectionTitle: {
    fontSize: 18,
    letterSpacing: 0.3,
  },
  headingIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headingIconPrimary: {
    backgroundColor: 'rgba(17,74,130,0.12)',
  },
  headingIconOrange: {
    backgroundColor: 'rgba(255,138,76,0.15)',
  },
  headingIconPurple: {
    backgroundColor: 'rgba(124,77,255,0.15)',
  },
  headingIconAmber: {
    backgroundColor: 'rgba(255,183,77,0.2)',
  },
  //PG
  sectionContainer: {
    paddingHorizontal: 16,
  },
  pgCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 16,
    marginTop: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    position: 'relative',
    borderWidth: 0.5,
    borderColor: '#E8E8E8',
  },
  pgInfoRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    width: '100%',
    marginBottom: 8,
  },
  pgTextContainer: {
    width: '100%',
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  pgAddressText: {
    marginLeft: 4,
    flexShrink: 1,
  },
  forPgContainer: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: colors.mainColor,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: 120,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  pgImage: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
  },

  categoryCard: {
    width: width / 2.5,
    marginRight: 12,
    alignItems: 'center',
    marginVertical: 8,
    backgroundColor: colors.white,
    padding: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    borderRadius: 16,
    borderWidth: 0.5,
    borderColor: '#E8E8E8',
  },
  categoryImage: {
    width: width / 3.2,
    height: width / 3.2,
    borderRadius: width / 3.2,
    resizeMode: 'cover',
    borderWidth: 3,
    borderColor: colors.mainColor,
  },

  scrollContainer: {
    paddingHorizontal: 5,
    paddingBottom: 15,
    paddingTop: 5,
  },
  card: {
    marginTop: 12,
    backgroundColor: colors.white,
    borderRadius: 18,
    width: 230,
    marginRight: 14,
    padding: 18,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    borderWidth: 0.5,
    borderColor: '#E8E8E8',
    minHeight: 220,
    position: 'relative',
  },
  stepHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 8,
    paddingRight: 48,
  },
  stepIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(17,74,130,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepTitleWrapper: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 15,
  },
  stepDesc: {
    marginTop: 4,
    lineHeight: 18,
  },
  stepBadgeWrapper: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 1,
  },
  stepNumberPill: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.mainColor,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  stepButton: {
    paddingVertical: 8,
    height: 40,
    borderRadius: 10,
    marginTop: 8,
    alignSelf: 'stretch',
  },
  whyCard: {
    width: 220,
    marginTop: 12,
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    marginRight: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    borderWidth: 0.5,
    borderColor: '#E8E8E8',
    minHeight: 140,
  },
  whyTitle: {
    marginBottom: 10,
    fontSize: 16,
  },

  reviewCard: {
    marginHorizontal: 2,
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
    marginVertical: 5,
    borderWidth: 0.5,
    borderColor: '#E8E8E8',
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 12,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 4,
    backgroundColor: '#D3D3D3',
  },
  paginationDotActive: {
    backgroundColor: colors.mainColor,
  },
});
