import { StyleSheet } from 'react-native';
import colors from '../../../../constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  listContent: {
    padding: 12,
    paddingBottom: 40,
    flexGrow: 1,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
    borderWidth: 1,
    borderColor: '#EEF2FF',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flex: 1,
  },
  nameText: {
    marginBottom: 6,
    color: colors.textDark || '#0F172A',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaText: {
    marginLeft: 6,
    color: '#475467',
    textDecorationLine: 'underline',
  },
  statusStack: {
    alignItems: 'flex-end',
    gap: 6,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusLabel: {
    color: '#94A3B8',
    fontSize: 12,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 50,
  },
  divider: {
    height: 1,
    backgroundColor: colors.logoBg,
    marginVertical: 14,
  },
  dateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  dateItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 0.3,
    borderColor: colors.logoBg,
    padding: 10,
    borderRadius: 12,
    marginRight: 10,
  },
  dateLabel: {
    color: '#7A869A',
    marginBottom: 2,
  },
  dateValue: {
    color: colors.textDark || '#0F172A',
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 6,
  },
  detailChip: {
    width: '32%',
    backgroundColor: '#F4F6FB',
    padding: 10,
    borderRadius: 12,
    marginBottom: 10,
  },
  detailLabel: {
    color: '#7A869A',
    marginBottom: 2,
  },
  detailValue: {
    color: colors.textDark || '#0F172A',
  },
  actionFooter: {
    borderTopWidth: 1,
    borderTopColor: colors.logoBg,
    paddingTop: 12,
    gap: 10,
  },
  actionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionLabel: {
    color: '#0F172A',
    fontWeight: '600',
  },
  actionHelper: {
    color: '#94A3B8',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  viewBtn: {
    height: 36,
    width: '25%',
    backgroundColor: 'undefined',
    borderColor: '#AEC8FF',
    borderWidth: 1,
  },
  paymentBtn: {
    width: '38%',
    height: 36,
    backgroundColor: 'undefined',
    borderColor: '#B7E7C2',
    borderWidth: 1,
  },
  inactiveBtn: {
    width: '28%',
    height: 36,
    backgroundColor: 'undefined',
    borderColor: '#FFD8A6',
    borderWidth: 1,
  },
  checkoutCard: {
    marginTop: 8,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#F8FAFF',
    borderWidth: 1,
    borderColor: '#E0E7FF',
    gap: 10,
  },
  checkoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  checkoutHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  checkoutTitle: {
    color: colors.textDark || '#0F172A',
    fontSize: 14,
  },
  checkoutContent: {
    marginTop: 6,
    gap: 6,
  },
  checkoutRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  checkoutLabel: {
    color: '#6B7280',
    fontSize: 12,
  },
  checkoutValue: {
    color: colors.textDark || '#0F172A',
    fontSize: 13,
  },
  checkoutReason: {
    color: colors.textDark || '#0F172A',
    fontSize: 13,
    flex: 1,
    textAlign: 'right',
  },
  checkoutActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 8,
  },
  checkoutAcceptBtn: {
    width: 90,
    height: 32,
    borderWidth: 1,
    borderColor: '#0E9F6E',
    backgroundColor: 'transparent',
  },
  checkoutRejectBtn: {
    width: 90,
    height: 32,
    borderWidth: 1,
    borderColor: '#DC2626',
    backgroundColor: 'transparent',
  },
  filterContainer: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    gap: 20,
  },
  filterTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterIconWrapper: {
    position: 'relative',
  },
  filterIconButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  filterBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#16A34A',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 3,
  },
  filterBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
  },
  filterRow: {
    gap: 12,
  },
  filterLabel: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
    marginBottom: 2,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    padding: 3,
    height: 40,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  segmentButtonLeft: {
    marginRight: 1.5,
  },
  segmentButtonRight: {
    marginLeft: 1.5,
  },
  segmentButtonActive: {
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  segmentButtonText: {
    color: '#9CA3AF',
    fontSize: 13,
    fontWeight: '500',
  },
  segmentButtonTextActive: {
    color: colors.mainColor,
    fontSize: 13,
    fontWeight: '600',
  },
  filterScrollContent: {
    gap: 10,
    paddingRight: 4,
  },
  filterChip: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: 10,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterChipActive: {
    backgroundColor: colors.mainColor,
    borderColor: colors.mainColor,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  filterText: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '500',
  },
  filterTextActive: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '600',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
  },
  rejectModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  rejectModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 18,
  },
  rejectModalTitle: {
    textAlign: 'center',
    marginBottom: 6,
  },
  rejectModalSubtitle: {
    textAlign: 'center',
    color: '#6B7280',
    marginBottom: 12,
  },
  rejectModalInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  rejectModalInfoLabel: {
    color: '#6B7280',
    fontSize: 12,
  },
  rejectModalInfoValue: {
    color: colors.textDark || '#0F172A',
    fontSize: 13,
  },
  rejectModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 35,
  },
  rejectCancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.mainColor,
    backgroundColor: 'transparent',
    height: 40,
  },
  rejectSubmitBtn: {
    flex: 1,
    height: 40,
  },
});
